name: update-readme

on:
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python .github/workflows/update.py
      - name: Commit changes (mit Abbruch bei "nothing to commit")
        run: |
          git config --global user.name 'Felix Schürmeyer'
          git config --global user.email '25571323+fschuermeyer@users.noreply.github.com'

          git add README.md

          if ! git commit -m "Update Article List on $(date +%Y-%m-%d)"; then
            echo "Keine Änderungen gefunden. Abbruch!"
            exit 0
          fi

          git push